---

# Get Wordpress
- name: Download Wordpress
  get_url:
    url: https://wordpress.org/{{ wp_version }}.tar.gz # Url
    dest: /tmp/wordpress.tar.gz # Destination
    force: yes

- name: Extract Wordpress
  unarchive: 
    src: /tmp/wordpress.tar.gz # Unzip and move to /var/www/html
    dest: /var/www
    copy: no
    creates: "{{ path }}"
  become: yes # Become sudo

# Config WP
- name: Generate random SALT
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt" # Insert salt in THIS variable => wp_salt
  become: no

- name: Add Wordpress config file
  template: 
    src: wp-config.j2
    dest: "{{ path }}/wp-config.php"
    force: no